apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rclone.csi.veloxpack.io
  name: pv-storyteller
  namespace: books
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: rclone.csi.veloxpack.io
    volumeHandle: data-id
    nodePublishSecretRef:
      name: rclone-drive
      namespace: kube-system
    volumeAttributes:
      remote: "drive"
      remotePath: "/#Storyteller"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storyteller
  namespace: books
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-storyteller
  storageClassName: ""
