apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: aiostreams
  namespace: istio-ingress
  labels:
    app: aiostreams
spec:
  hosts:
    - "aiostreams.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 3000
            host: aiostreams.streaming.svc.cluster.local
