apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: breezewiki
  namespace: istio-ingress
  labels:
    app: breezewiki
spec:
  hosts:
    - "breeze.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 10416
            host: breezewiki.breezewiki.svc.cluster.local
