apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: calibre-downloader
  namespace: istio-ingress
  labels:
    app: calibre
spec:
  hosts:
    - "cdownloader.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8084
            host: calibre-downloader.books.svc.cluster.local
