apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: homepage
  namespace: istio-ingress
  labels:
    app: homepage
spec:
  hosts:
    - "auth.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 80
            host: homepage.homepage.svc.cluster.local
