apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jackett
  namespace: istio-ingress
  labels:
    app: jackett
spec:
  hosts:
    - "jackett.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 9117
            host: arr-jackett.arr.svc.cluster.local
