apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jellyfin
  namespace: istio-ingress
  labels:
    app: argocd
spec:
  hosts:
    - "jellyfin.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8096
            host: jellyfin.streaming.svc.cluster.local
