apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
  namespace: istio-ingress
  labels:
    app: keycloak
    protected: "false"
spec:
  hosts:
    - "auth.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /oauth2/callback
      route:
        - destination:
            port:
              number: 80
            host: oauth2-proxy.keycloak.svc.cluster.local
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8080
            host: keycloak.keycloak.svc.cluster.local
