apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pgadmin
  namespace: istio-ingress
spec:
  hosts:
    - "auth.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8080
            host: keycloak.keycloak.svc.cluster.local
