apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oauth
  namespace: istio-ingress
  labels:
    app: oauth
spec:
  hosts:
    - "*.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /oauth2/callback
      route:
        - destination:
            port:
              number: 80
            host: oauth2-proxy.keycloak.svc.cluster.local
