apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: plex
  namespace: istio-ingress
  labels:
    app: argocd
spec:
  hosts:
    - "plex.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 32400
            host: plex.streaming.svc.cluster.local
