apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prowlarr
  namespace: istio-ingress
  labels:
    app: prowlarr
spec:
  hosts:
    - "prowlarr.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 9696
            host: streaming-prowlarr.streaming.svc.cluster.local
