apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: storyteller
  namespace: istio-ingress
  labels:
    app: storyteller
spec:
  hosts:
    - "storyteller.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8001
            host: storyteller.storyteller.svc.cluster.local
