apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: suwayomi
  namespace: istio-ingress
  labels:
    app: argocd
spec:
  hosts:
    - "suwayomi.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 4567
            host: suwayomi.books.svc.cluster.local
