apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vault
  namespace: istio-ingress
  labels:
    app: vault
    protected: false
spec:
  hosts:
    - "vault.adryan.me"
  gateways:
    - public
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8200
            host: vault.vault.svc.cluster.local
