apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali
  namespace: operators
spec:
  channel: stable
  name: kiali
  source: operatorhubio-catalog
  sourceNamespace: olm
