apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shulker-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: shulker-operator
spec:
  project: default
  source:
    repoURL: https://github.com/jeremylvln/Shulker.git
    path: ./kube/helm
    targetRevision: v0.13.0
    helm:
      valuesObject:
        metrics:
          enabled: true
          servicemonitor:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: shulker-system

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
