apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: default-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: adryan1990@gmail.com
            apiKeySecretRef:
              name: cloudflare-key
              key: api-key
