apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-key
  namespace: keycloak
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-key
  data:
    - secretKey: api-key
      remoteRef:
        key: cert-manager/cloudflare-key
        property: key
