{{- if eq (include "workload.enabled" (dict "root" . "name" "comet")) "true" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: comet-env
  namespace: comet
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: comet-env
  data:
    - secretKey: ADMIN_DASHBOARD_PASSWORD
      remoteRef:
        key: comet/app
        property: ADMIN_DASHBOARD_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: storage/sphere-comet
        property: uri
{{- end }}
