apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dmb-secrets
  namespace: streaming
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: dmb-secrets
  data:
    - secretKey: RCLONE_INSTANCES_REALDEBRID_API_KEY
      remoteRef:
        key: streaming/dmb
        property: real-debrid-api-key
    - secretKey: RIVEN_BACKEND_ENV_RIVEN_DATABASE_HOST
      remoteRef:
        key: storage/sphere-riven
        property: fqdn-uri
    - secretKey: RIVEN_FRONTEND_ENV_DATABASE_URL
      remoteRef:
        key: storage/sphere-riven
        property: fqdn-uri
    - secretKey: ZILEAN_ENV_Zilean__Database__ConnectionString
      remoteRef:
        key: storage/sphere-zilean
        property: fqdn-uri
    - secretKey: ZURG_INSTANCES_REALDEBRID_USER
      remoteRef:
        key: streaming/dmb
        property: real-debrid-user
    - secretKey: ZURG_INSTANCES_REALDEBRID_PASSWORD
      remoteRef:
        key: streaming/dmb
        property: real-debrid-pass
    - secretKey: ZURG_INSTANCES_REALDEBRID_API_KEY
      remoteRef:
        key: streaming/dmb
        property: real-debrid-api-key
