apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-password
  namespace: keycloak
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-password
  data:
    - secretKey: password
      remoteRef:
        key: keycloak/admin-password
        property: password
