apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rcon
  namespace: minecraft
spec:
  refreshInterval: "24h"
  target:
    name: rcon
    template:
      data:
        rcon-password: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: "general-passgen"