{{- if eq (include "workload.enabled" (dict "root" . "name" "netbird")) "true" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-operator-api-key
  namespace: netbird
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: netbird-operator-api-key
  data:
    - secretKey: NB_API_KEY
      remoteRef:
        key: netbird/operator-api-key
        property: token
{{- end }}
