{{- if eq (include "workload.enabled" (dict "root" . "name" "netbird")) "true" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-relay
  namespace: netbird
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: netbird-relay
  data:
    - secretKey: secret
      remoteRef:
        key: netbird/relay-auth
        property: secret
    - secretKey: datastoreEncryptionKey
      remoteRef:
        key: netbird/relay-auth
        property: datastoreEncryptionKey
{{- end }}
