apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sphere-riven
  namespace: streaming
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: riven-db-credentials
  data:
    - secretKey: RIVEN_DATABASE_HOST
      remoteRef:
        key: storage/sphere-riven
        property: fqdn-uri
