apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: atium-public
  namespace: shulker-system
spec:
  clusterRef:
    name: atium
  replicas: 1
  service:
    type: NodePort
    externalTrafficPolicy: Local
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      config: {}
