apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: atium-fleet
  namespace: shulker-system
spec:
  clusterRef:
    name: atium
  replicas: 1
  template:
    spec:
      clusterRef:
        name: atium
      tags:
        - lobby
      version:
        channel: Paper
        name: "1.21.10"
      config: {}
