apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: oauth2-general
spec:
  selector:
    matchLabels:
      protected: true
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - "*"
