apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: oauth2-general
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: gateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              [
                "longhorn.adryan.me",
                "grafana.adryan.me",
                "kiali.adryan.me",
                "cdownloader.adryan.me",
                "arr.adryan.me",
                "riven.adryan.me",
              ]
