---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curseforge-api-key
  namespace: minecraft
spec:
  encryptedData:
    cf-api-key: AgAaYn/VmSC9ruBVYSDf6Iz7nx9g9evAkl70fxhXj9wUHrPESCOIOG0IusxJNggQ5UxZFzEP6AbjnfaspciGFPJd80lTczCJfRKs8JUgKV5H0Y5pp9o5lzhbUcbfc/BW8Nw+vuTukTNL/Bia1/thJoLNpe7895j0CT0a3ZGueSkizcGQoO5Gsp/3xttBjptik9w/blgF+7BE88rA29lrl6h2+HEFy1Jqhs8DYLVWUzQnByMF4C4AzeTriV3hZyw8TRmffpUY5l+/fI/QXkRuiJcjv7pi1XyGIVuWNxTbl9M++43IdNU3LStDjtNHURjUF/srYVVab3jgeAldPsqOxyz2uxeLzSNYl25/pyugdBoqS+rDgTbCf82hsvzrHpH+9fezNcO7boVf1fz5ozlsqWn/CQqYLer7JXs3graHNzMLYr8Qs+eUP/bn+IazoCW1ADALcj3T1HZh3nAoBP/VDWLa5Ui3eOt37ty7cEy11zWxMKIQsOZhS8H7NTAlY23NUlrDv08SbFhQuR22/un1Pg0eSnP+hYRT+mxHYFhyVjkGvXO4tcrNcT4wsNMlc9f+5SPtkdPwXOQItynY8a0bG73BCyHouehXLqu6mNlctSTbHzRw/ONIJ1K62CT4AuDGMzO63Q6A0o0mRhgg2gBWlWwf0HTltKGm8t7NzET/PLNKb16bAEIfGilYse+x4uD0SENyj29vDqBFb/id8AQSpI+Cmu27gkceGI5XpEH5zk5bQ28xUIckhwnUD9k9S40mJkIwCO1Kup7byHXooLo=
  template:
    metadata:
      creationTimestamp: null
      name: curseforge-api-key
      namespace: minecraft
    type: Opaque
