apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minecraft
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.23.2
    chart: minecraft
    helm:
      releaseName: minecraft
      valuesObject:
        resources:
          requests:
            memory: 2048M
        minecraftServer:
          eula: true
          difficulty: normal
          motd: "Bem-vindo ao servidor da Terceira Guilda"
          onlineMode: false
          overrideServerProperties: true
          memory: 2048M
          autoCurseForge:
            apiKey:
              existingSecret: curseforge-api-key
        persistance:
          dataDir:
            enabled: true
            Size: 5Gi
  syncPolicy:
    automated: 
    syncOptions:
    - CreateNamespace=true
