apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minecraft
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.23.2
    chart: minecraft
    helm:
      releaseName: minecraft
      valuesObject:
        extraDeploy:
          - |
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: minecraft
              namespace: minecraft
            spec:
              ingressClassName: nginx
              rules:
              - http:
                  paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: minecraft-minecraft
                        port:
                          name: minecraft
                host: mc.adryan.me
        resources:
          requests:
            memory: 2048M
        minecraftServer:
          eula: true
          difficulty: normal
          motd: "Bem-vindo ao servidor da Terceira Guilda"
          onlineMode: false
          overrideServerProperties: true
          memory: 2048M
          autoCurseForge:
            apiKey:
              existingSecret: curseforge-api-key
        persistance:
          dataDir:
            enabled: true
            Size: 5Gi
  syncPolicy:
    automated: 
    syncOptions:
    - CreateNamespace=true
