apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-user
  namespace: storage
spec:
  refreshInterval: "24h"
  target:
    name: sphere-app
    creationPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ `{{ .password }}` }}"
        pgpass: "sphere-rw:5432:app:app:{{`{{ .password }}`}}"
        jdbc-uri: "jdbc:postgresql://sphere-rw.storage.svc.cluster.local:5432/app?password={{`{{ .password }}`}}&user=app"
        uri: "postgresql://app:{{`{{ .password }}`}}@sphere-rw.storage.svc.cluster.local:5432/app"
        fqdn-jdbc-uri: "jdbc:postgresql://sphere-rw.storage.svc.cluster.local:5432/app?password={{`{{ .password }}`}}&user=app"
        fqdn-uri: "postgresql://app:{{`{{ .password }}`}}@sphere-rw.storage.svc.cluster.local:5432/app"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: "cnpg-passgen"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: app-user-pushsecret
  namespace: storage
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: sphere-app
  data:
    - match:
        remoteRef:
          remoteKey: storage/sphere-app
