apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-user
  namespace: storage
spec:
  refreshInterval: "24h"
  target:
    name: sphere-app
    creationPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password | b64dec }}"
        pgpass: "sphere-rw:5432:app:app:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://sphere-rw.default:5432/app?password={{ .password }}&user=app"
        uri: "postgresql://app:{{ .password }}@sphere-rw.default:5432/app"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: cnpg-passgen
