apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zilean-user
  namespace: storage
spec:
  refreshInterval: "24h"
  target:
    name: sphere-zilean
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ `{{ .password }}` }}"
        pgpass: "sphere-rw:5432:zilean:zilean:{{`{{ .password }}`}}"
        jdbc-uri: "jdbc:postgresql://sphere-rw.default:5432/zilean?password={{`{{ .password }}`}}&user=zilean"
        uri: "postgresql://zilean:{{`{{ .password }}`}}@sphere-rw.default:5432/zilean"
        fqdn-jdbc-uri: "jdbc:postgresql://sphere-rw.storage.svc.cluster.local:5432/zilean?password={{`{{ .password }}`}}&user=zilean"
        fqdn-uri: "Host=sphere-rw.storage.svc.cluster.local;Database=zilean;Username=zilean;Password={{ `{{ .password }}` }};Include Error Detail=true;Timeout=30;CommandTimeout=3600;"
        # fqdn-uri: "postgresql+psycopg2://zilean:{{`{{ .password }}`}}@sphere-rw.storage.svc.cluster.local:5432/zilean"
        port: "5432"
        host: "sphere-rw"
        user: "zilean"
        username: "zilean"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: "cnpg-passgen"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: zilean-user-pushsecret
  namespace: storage
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: sphere-zilean
  data:
    - match:
        remoteRef:
          remoteKey: storage/sphere-zilean
