apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sphere
  namespace: storage
spec:
  instances: 2
  storage:
    size: 10Gi
  managed:
    roles:
      - name: app
        createdb: true
        login: true
        superuser: true
      - name: keycloak
        createdb: false
        login: true
        passwordSecret:
          name: sphere-keycloak
      - name: riven
        createdb: false
        login: true
        passwordSecret:
          name: sphere-riven
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak-db
  namespace: storage
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: sphere
  schemas:
    - name: keycloak
      owner: keycloak
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: riven-db
  namespace: storage
spec:
  name: riven
  owner: riven
  cluster:
    name: sphere
  schemas:
    - name: riven
      owner: riven
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: zilean-db
  namespace: storage
spec:
  name: zilean
  owner: zilean
  cluster:
    name: sphere
  schemas:
    - name: zilean
      owner: zilean
