apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sphere
  namespace: storage
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: sphere
  podMetricsEndpoints:
    - port: metrics
