apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-ns-eso-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-source-secret
  namespace: default
rules:
  - apiGroups: [""]
    resourceNames:
      - source-secret
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-source-secret
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default-ns-eso-sa
    namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: read-source-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default-ns
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: operators
      auth:
        serviceAccount:
          name: "default-ns-eso-sa"
          namespace: "default"
