apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: broam
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  postgresVersion: 17
  users:
    - name: potato
      databases:
        - authentik
        - aiostreams
      options: "SUPERUSER"
    - name: authentik
      databases:
        - authentik
    - name: aiostreams
      databases:
        - aiostreams
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "hostnossl all all all password"
  instances:
    - name: broam-001
      dataVolumeClaimSpec:
        storageClassName: longhorn
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
    - name: broam-002
      dataVolumeClaimSpec:
        storageClassName: longhorn
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
