apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minecraft
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.23.2
    chart: minecraft
    helm:
      releaseName: minecraft
      valuesObject:
        minecraftServer:
          eula: true
        persistance:
          dataDir:
            enabled: true
            Size: 5Gi
  syncPolicy:
    automated: 
    syncOptions:
    - CreateNamespace=true
