apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: calibre
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.4.0
    chart: app-template
    helm:
      valuesObject:
        controllers:
          main:
            containers:
              main:
                image:
                  repository: crocodilestick/calibre-web-automated
                  tag: latest
                env:
                  PUID: "1000"
                  PGID: "1000"
                  TZ: "America/Bahia"
                  CWA_PORT_OVERRIDE: "8083"
        service:
          main:
            controller: main
            ports:
              http:
                port: 8083
        persistence:
          config:
            accessMode: ReadWriteOnce
            size: 1Gi
            type: persistentVolumeClaim
            globalMounts:
              - path: /config
          ingest:
            accessMode: ReadWriteOnce
            size: 4Gi
            type: persistentVolumeClaim
            globalMounts:
              - path: /cwa-book-ingest
          library:
            accessMode: ReadWriteOnce
            size: 20Gi
            type: persistentVolumeClaim
            globalMounts:
              - path: /calibre-library

  destination:
    server: https://kubernetes.default.svc
    namespace: books

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
