{{- if eq (include "workload.enabled" (dict "enabled" true)) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: cert-manager
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: 1.19.1
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: cert-manager

  {{- include "workload.syncPolicy" (dict "profile" "platform") | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
