{{- if eq (include "workload.enabled" (dict "root" . "name" "cert-manager")) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: cert-manager
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.21.1
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
        resources:
          requests:
            cpu: 5m
        cainjector:
          resources:
            requests:
              cpu: 5m
        webhook:
          resources:
            requests:
              cpu: 5m

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: cert-manager

  {{- include "workload.syncPolicy" (dict "profile" "platform") | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
