{{- if eq (include "workload.enabled" (dict "enabled" true)) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-rclone
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: csi-driver-rclone
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/veloxpack/csi-driver-rclone-charts
    targetRevision: 1.0.0
    path: .
    helm:
      valuesObject:
        node:
          metrics:
            enbled: true
            service:
              enabled: true
            serviceMonitor:
              enabled: true
            dashboard:
              enabled: true
              namespace: monitoring

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: kube-system

  {{- include "workload.syncPolicy" (dict "profile" "platform") | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
