apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devices
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: devices
spec:
  project: default
  source:
    repoURL: https://charts.gabe565.com
    targetRevision: 0.1.3
    chart: generic-device-plugin
    helm:
      valuesObject:
        env:
          DOMAIN: adryan.me

  destination:
    server: https://kubernetes.default.svc
    namespace: streaming

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
