apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: jellyfin
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.4.0
    chart: app-template
    helm:
      valuesObject:
        controllers:
          jellyfin:
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              jellyfin:
                image:
                  repository: lscr.io/linuxserver/jellyfin
                  tag: latest
                  pullPolicy: Always
                env:
                  PGID: 1000
                  PUID: 1000
                  TZ: America/Bahia
        service:
          jellyfin:
            controller: jellyfin
            ports:
              http:
                port: 8096
        persistence:
          config:
            accessMode: ReadWriteOnce
            size: 10Gi
            type: persistentVolumeClaim
          riven:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: streaming-riven-library
            globalMounts:
              - path: /library
          zurg-mount:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: zurg
            globalMounts:
              - path: /rclone

  destination:
    server: https://kubernetes.default.svc
    namespace: streaming

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
