{{- if eq (include "workload.enabled" (dict "root" . "name" "keycloak")) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: keycloak
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/cloudpirates/keycloak
    targetRevision: 0.8.4
    path: .
    helm:
      valuesObject:
        commonAnnotations:
          reloader.stakater.com/auto: "true"
        keycloak:
          production: true
          proxyHeaders: xforwarded
          adminUser: admin
          existingSecret: keycloak-admin-password
          secretKeys:
            adminPasswordKey: password
          hostname: auth.adryan.me
        database:
          type: postgres
          host: sphere-rw.storage.svc.cluster.local
          port: "5432"
          schema: keycloak
          existingSecret: "keycloak-db-credentials"
          secretKeys:
            usernameKey: "username"
            passwordKey: "password"
        postgres:
          enabled: false
        cache:
          stack: ispn
        server:
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 2Gi

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: keycloak

  info:
    - name: "Homepage:"
      value: "https://auth.adryan.me"

  {{- include "workload.syncPolicy" (dict "profile" "platform") | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
