{{- if eq (include "workload.enabled" (dict "root" . "name" "metrics-server")) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: metrics-server
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.13.0
    chart: metrics-server
    helm:
      valuesObject:
        replicas: 1
        defaultArgs:
          - --cert-dir=/tmp
          - --kubelet-preferred-address-types=ExternalIP
          - --kubelet-use-node-status-port
          - --metric-resolution=15s

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: kube-system

  {{- include "workload.syncPolicy" (dict "profile" "platform" "serverSideApply" true "respectIgnoreDifferences" true) | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
