apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: minecraft
spec:
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 5.0.0
    chart: minecraft
    helm:
      valuesObject:
        replicaCount: 1
        podAnnotations:
          reloader.stakater.com/auto: "true"
        resources:
          requests:
            cpu: 1m
            memory: 1Gi
          limits:
            memory: 2Gi
        minecraftServer:
          eula: "TRUE"
          version: "1.21.11"
          type: "PAPER"
          ops: adryan29
          onlineMode: false
          motd:  "== Bem vindo ao servidor do Leo! =="
          serviceType: LoadBalancer
          whitelist: adryan29,Andrey
          rcon:
            enabled: true
            serviceType: LoadBalancer
            existingSecret: rcon
          mcbackup:
            enabled: true
            backupInterval: 24h
            linkLatest: "true"
            persistance:
              storageClass: "longhorn-low"
              backupDir:
                enabled: true
                Size: 10Gi
          pluginUrls:
            - "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
            - "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
            - "https://cdn.modrinth.com/data/Lu3KuzdV/versions/HD2IvrxS/CoreProtect-CE-23.1.jar"
          extraPorts:
            - name: geyser
              containerPort: 19132
              protocol: UDP
              service:
                enabled: true
                type: LoadBalancer
                port: 19132
        persistence:
          storageClass: "longhorn-low"
          dataDir:
            enabled: true
            Size: 5Gi
            existingClaim: minecraft

  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
