apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: minecraft
spec:
  project: default
  source:
    repoURL: https://itzg.github.io/minecraft-server-charts
    targetRevision: 5.0.0
    chart: minecraft
    helm:
      valuesObject:
        minecraftServer:
          eula: "TRUE"
          version: "1.21.10"
          type: "PAPER"
          ops: adryan29
          onlineMode: false
          serviceType: LoadBalancer
          pluginUrls:
            - "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
            - "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
          extraPorts:
            - name: geyser
              containerPort: 19132
              protocol: UDP
              service:
                enabled: true
                type: LoadBalancer
                port: 19132
        persistence:
          storageClass: "longhorn-low"
          dataDir:
            enabled: true
            size: 2Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
