apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: monitoring
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
    targetRevision: 79.5.0
    path: .
    helm:
      valuesObject:
        global:
          rbac:
            createAggregateClusterRoles: true
        prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
        nameOverride: monitoring
        fullnameOverride: monitoring
        grafana:
          admin:
            existingSecret: monitoring-grafana-admin
            userKey: user
            passwordKey: password
          persistence:
            enabled: true
            accessModes:
              - ReadWriteOnce
            size: 5Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  ignoreDifferences:
    - kind: "ConfigMap"
      namespace: monitoring
      jsonPointers:
        - /data/grafana.ini

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istion-injection: enabled
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
