apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
  namespace: default
spec:
  serviceName: "pgadmin"
  users:
    - username: root@adryan.me
      role: Administrator
      passwordRef:
        name: pgadmin-root-password
        key: password
  dataVolumeClaimSpec:
    storageClassName: longhorn
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: 1Gi
  serverGroups:
    - name: supply
      postgresClusterSelector: {}
    - name: name-discovery
      postgresClusterName: broam
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
spec:
  tls:
  - hosts:
      - pg.adryan.me
    secretName: adryan.me-tls
  rules:
  - host: pg.adryan.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pgadmin
            port: 
              number: 5050