{{- if eq (include "workload.enabled" (dict "root" . "name" "reloader")) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: reloader
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.2.5
    chart: reloader

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: kube-system

  {{- include "workload.syncPolicy" (dict "profile" "platform" "serverSideApply" true "respectIgnoreDifferences" true) | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
