{{- if eq (include "workload.enabled" (dict "root" . "name" "storyteller")) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storyteller
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: storyteller
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.6.2
    chart: app-template
    helm:
      valuesObject:
        controllers:
          main:
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              main:
                image:
                  repository: registry.gitlab.com/storyteller-platform/storyteller
                  tag: latest
                  pullPolicy: Always
                env:
                  ENABLE_WEB_READER: true
                envFrom:
                  - secretRef:
                      name: storyteller-env
                resources:
                  requests:
                    cpu: 1m
                    memory: 2Gi
                  limits:
                    cpu: 4000m
                    memory: 24Gi
        service:
          main:
            controller: main
            ports:
              http:
                port: 8001
        persistence:
          data:
            accessMode: ReadWriteOnce
            size: 40Gi
            type: persistentVolumeClaim

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: books

  {{- include "workload.syncPolicy" (dict "profile" "workload") | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
