apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storyteller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: storyteller
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.4.0
    chart: app-template
    helm:
      valuesObject:
        controllers:
          main:
            containers:
              main:
                image:
                  repository: registry.gitlab.com/storyteller-platform/storyteller
                  tag: latest
                envFrom:
                  - secretRef:
                      name: storyteller-env
        service:
          main:
            controller: main
            ports:
              http:
                port: 8001

  destination:
    server: https://kubernetes.default.svc
    namespace: storyteller

  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istion-injection: enabled
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
