{{- if eq (include "workload.enabled" (dict "root" . "name" "tailscale")) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: tailscale
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.94.1
    chart: tailscale-operator

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: tailscale

  {{- include "workload.syncPolicy" (dict "profile" "workload" "istioInjection" "disabled") | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
