apiVersion: tor.k8s.torproject.org/v1alpha2
kind: Tor
metadata:
  name: tor
  namespace: streaming
spec:
  metrics:
    enable: true
    address: 0.0.0.0
    port: 9035
    policy: accept 0.0.0.0/0
  serviceMonitor: true
