{{- if eq (include "workload.enabled" (dict "enabled" true)) "true" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    {{- include "workload.finalizers" . | nindent 4 }}
  labels:
    name: vault
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.31.0
    chart: vault
    helm:
      valuesObject:
        server:
          readinessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
          livenessProbe:
            enabled: true
            path: "/v1/sys/health?standbyok=true"
            initialDelaySeconds: 60
        ui:
          enabled: true

  destination:
    server: {{ include "workload.destinationServer" . }}
    namespace: vault

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle

  info:
    - name: "Homepage:"
      value: "https://vault.adryan.me"

  {{- include "workload.syncPolicy" (dict "profile" "platform") | nindent 2 }}
  revisionHistoryLimit: {{ include "workload.revisionHistoryLimit" . }}
{{- end }}
