apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-drive
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: rclone-drive
  dataFrom:
    - extract:
        key: rclone/drive
