{{- if eq (include "workload.enabled" (dict "root" . "name" "csi-driver-rclone")) "true" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: storyteller-library-drive
  namespace: kube-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: storyteller-library-drive
  dataFrom:
    - extract:
        key: storyteller/library-drive
{{- end }}
