apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: public
  namespace: istio-ingress
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: adryan.me-tls
      hosts:
        - "*"
