apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: rclone.csi.veloxpack.io
  name: zurg
  namespace: streaming
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: rclone.csi.veloxpack.io
    volumeHandle: data-id
    volumeAttributes:
      remote: "zurg"
      remotePath: "/"
      configData: |
        [zurg]
        type = webdav
        url = http://streaming-zurg.streaming.svc.cluster.local:9999/dav
        vendor = other
        pacer_min_sleep = 0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zurg
  namespace: streaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: zurg
  storageClassName: ""
